//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotlar
    {
        public int NotId { get; set; }
        public Nullable<byte> VizeNotu { get; set; }
        public Nullable<byte> FinalNotu { get; set; }
        public Nullable<byte> ButunlemeNotu { get; set; }
        public Nullable<int> DersId { get; set; }
        public Nullable<int> OgrId { get; set; }
    
        public virtual TblDersler TblDersler { get; set; }
        public virtual TblOgrenci TblOgrenci { get; set; }
    }
}
