//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int NotId { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public string DersAd { get; set; }
        public Nullable<byte> VizeNotu { get; set; }
        public Nullable<byte> FinalNotu { get; set; }
        public Nullable<byte> ButunlemeNotu { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
    }
}
